# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moziomaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='polygon_area',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='coordinates',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
